#!/bin/bash

function main() {
	
	#copy vimrc
	rsync -av ./vim/.vimrc ~/

	#copy tmux config
	rsync -av ./tmux/.tmux.conf ~/

	#these are the optional configs
	if [ "$1" == "all" ]; then
		#copy mcomix configs
		rsync -av ./mcomix ~/.config/

		#copy mpv configs
		rsync -av ./mpv ~/.config/
	fi
}

main $@
