#!/bin/bash

function main() {
	
	#copy vimrc
	rsync -a --progress ./vim/.vimrc ~/

	#copy tmux config
	rsync -a --progress ./tmux/.tmux.conf ~/

	# deploy .[something]rc files
	rsync -a --progress ./rc/ ~/

    # copy nvim config
    rsync -a --progress ./nvim ~/.config/nvim

	#these are the optional configs
	if [ "$1" == "all" ]; then
		#copy mcomix configs
		rsync -a -progress ./mcomix ~/.config/

		#copy mpv configs
		rsync -a -progress ./mpv ~/.config/
	fi
}

main $@
