#!/bin/bash

function main() {
	
	#copy vimrc
	rsync -av ./vim/.vimrc ~/

	#copy mpv configs
	rsync -av ./mpv ~/.config/

	#these are the optional configs
	if [ "$1" == "all" ]; then
		#copy mcomix configs
		rsync -av ./mcomix ~/.config/

		#copy tmux config
		rsync -av ./tmux/.tmux.conf ~/
	fi
}

main $@
